# Libraries for scientific research

In [1]:
import numpy

In [3]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [4]:
arthritis = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [5]:
print(arthritis)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [6]:
print(type(arthritis))

<class 'numpy.ndarray'>


## Attributes (adjectives)

In [7]:
print(arthritis.dtype)
print(arthritis.shape)

float64
(60, 40)


In [8]:
print("first value in arthritis:", arthritis[0,0])

first value in arthritis: 0.0


In [9]:
print("middle value in arthritis:", arthritis[30,20])

middle value in arthritis: 13.0


In [10]:
print(arthritis[0:4,0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [11]:
print(arthritis[5:10,0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [15]:
corner = arthritis[:3, 36:]
print(corner)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


## Exercise

In [16]:
"oxygen"[1:3]

'xy'

In [17]:
"oxygen"[1:4]

'xyg'

# Operations

In [21]:
double_arthritis = arthritis * 2

In [22]:
print("original")
print(arthritis[:3,36:])
print("double")
print(double_arthritis[:3,36:])

original
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]
double
[[4. 6. 0. 0.]
 [2. 2. 0. 2.]
 [4. 4. 2. 2.]]


In [25]:
triple_arthritis = double_arthritis + arthritis
print(triple_arthritis[:3, 36:])

[[6. 9. 0. 0.]
 [3. 3. 0. 3.]
 [6. 6. 3. 3.]]


# Methods(verbs)

In [26]:
print(arthritis.mean())

6.14875


In [27]:
print("maximum inflammation:", arthritis.max())
print("minimum inflammation:", arthritis.min())
print("standard deviation:", arthritis.std())

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [28]:
arthritis.size

2400

In [29]:
patient_0 = arthritis[0,:]
print("maximum inflammation for patient 0", patient_0.max())

maximum inflammation for patient 0 18.0


In [32]:
print("maximum inflammation for patient 2", arthritis[2,:].max())

maximum inflammation for patient 2 19.0


In [33]:
print(arthritis.max(axis=1))

[18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]


In [43]:
print(arthritis.max(axis=0))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 19. 18. 17. 16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.
  4.  3.  2.  1.]


In [44]:
print(arthritis.max(axis=1).shape) #max in one patient row
print(arthritis.max(axis=0).shape) #maximum in day colum
print(arthritis.shape)

(60,)
(40,)
(60, 40)


In [39]:
print(arthritis.std(axis=1))

[3.89839711 4.32369923 4.7581509  4.2708313  4.05555175 4.74071461
 4.20409027 5.2179977  4.61349921 5.05958249 5.03233296 4.31972221
 4.23961968 4.42012443 4.22780972 4.48441746 4.87314067 4.69680743
 4.42464688 5.09386886 4.86049123 3.99929681 4.80045571 4.59782557
 4.74447047 4.66308642 5.03959324 4.69301342 4.80045571 5.0593972
 4.34101083 4.48079234 4.31849221 4.20230591 5.54701496 4.47765284
 4.08281459 4.98773496 4.9415964  4.63546114 4.66094143 4.53865343
 4.49555336 4.50444225 4.46514277 3.86902766 5.37348816 4.53072842
 4.15301096 4.80097646 3.81575681 4.94873721 4.67379664 4.0895446
 5.02487562 4.00749298 4.84639041 4.47660586 4.71142229 4.54312668]


In [40]:
arthritis[2,:]

array([ 0.,  1.,  1.,  3.,  3.,  2.,  6.,  2.,  5.,  9.,  5.,  7.,  4.,
        5.,  4., 15.,  5., 11.,  9., 10., 19., 14., 12., 17.,  7., 12.,
       11.,  7.,  4.,  2., 10.,  5.,  4.,  2.,  2.,  3.,  2.,  2.,  1.,
        1.])