# Libraries for scientific research

In [1]:
import numpy

In [3]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [4]:
arthritis = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [5]:
print(arthritis)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [6]:
print(type(arthritis))

<class 'numpy.ndarray'>


## Attributes (adjectives)

In [7]:
print(arthritis.dtype)
print(arthritis.shape)

float64
(60, 40)


In [8]:
print("first value in arthritis:", arthritis[0,0])

first value in arthritis: 0.0


In [9]:
print("middle value in arthritis:", arthritis[30,20])

middle value in arthritis: 13.0


In [10]:
print(arthritis[0:4,0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [11]:
print(arthritis[5:10,0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [15]:
corner = arthritis[:3, 36:]
print(corner)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


## Exercise

In [16]:
"oxygen"[1:3]

'xy'

In [17]:
"oxygen"[1:4]

'xyg'